# Generated by Django 6.0.4 on 2026-04-19 13:28

import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resumes.models.resume_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('job_role', models.CharField(blank=True, default='General', max_length=200)),
                ('batch_date', models.DateField(auto_now_add=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('parse_confidence', models.FloatField(default=0.0)),
                ('raw_text', models.TextField(blank=True)),
                ('parsed_sections', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
